{% set name = "anytree" %}
{% set version = "2.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anytree-{{ version }}.tar.gz
  sha256: c9d3aa6825fdd06af7ebb05b4ef291d2db63e62bb1f9b7d9b71354be9d362714

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }},<4.0
    - six

test:
  imports:
    - anytree
    - anytree.node
    - anytree.iterators
    - anytree.importer
    - anytree.exporter
    - anytree.util
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/c0fec0de/anytree
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python tree data library'
  description: |
    'Python tree data library'
  doc_url: https://anytree.readthedocs.io/en/2.8.0
  dev_url: https://github.com/c0fec0de/anytree

extra:
  recipe-maintainers:
    - tlestang
    - jan-janssen
